// 02-data.js - Demo fixtures: course catalogue and user directory.

"use strict";

const courses = [
  {
    id: 1,
    title: "Deeskalation im Einsatz",
    module: "Bildung",
    type: "Präsenz",
    date: "2026-10-15",
    day: "15",
    month: "OKT",
    place: "Fortbildungszentrum NRW",
    time: "09:00–16:00 Uhr",
    duration: "2 Tage",
    seats: 8,
    category: "Kommunikation",
    desc: "Gesprächsführung in herausfordernden Situationen. Praktische Übungen, Reflexion und kollegialer Austausch.",
    approval: true,
  },
  {
    id: 2,
    title: "Datenschutz im Polizeialltag",
    module: "Bildung",
    type: "E-Learning",
    date: "2026-10-01",
    day: "01",
    month: "OKT",
    place: "Angeschlossenes LMS",
    time: "Zeitlich flexibel",
    duration: "90 Minuten",
    seats: 40,
    category: "Recht & Verwaltung",
    desc: "Sicherer Umgang mit personenbezogenen Daten. Fachliche Grundlagen und anwendungsbezogene Fallbeispiele.",
    approval: false,
  },
  {
    id: 3,
    title: "Einsatztraining: Sicher im Team",
    module: "Einsatztraining",
    type: "Präsenz",
    date: "2026-10-08",
    day: "08",
    month: "OKT",
    place: "Trainingszentrum NRW",
    time: "08:30–12:30 Uhr",
    duration: "4 Stunden",
    seats: 3,
    category: "Einsatzkompetenz",
    desc: "Abgestimmtes Handeln und sichere Abläufe im Team. Vertiefung der Grundlagen in angeleiteten Übungen.",
    approval: true,
  },
  {
    id: 4,
    title: "Funktionelles Training",
    module: "Sport",
    type: "Präsenz",
    date: "2026-10-09",
    day: "09",
    month: "OKT",
    place: "Sportzentrum NRW",
    time: "10:00–11:30 Uhr",
    duration: "90 Minuten",
    seats: 5,
    category: "Gesundheit & Fitness",
    desc: "Beweglichkeit, Kraft und Stabilität für den Dienstalltag. Individuell angepasste Übungsintensität.",
    approval: false,
  },
  {
    id: 5,
    title: "Digitale Zusammenarbeit",
    module: "Bildung",
    type: "E-Learning",
    date: "2026-10-12",
    day: "12",
    month: "OKT",
    place: "Angeschlossenes LMS",
    time: "Zeitlich flexibel",
    duration: "2 Stunden",
    seats: 30,
    category: "Digitale Kompetenz",
    desc: "Werkzeuge und Methoden für die Zusammenarbeit in verteilten Teams.",
    approval: false,
  },
  {
    id: 6,
    title: "Gesprächsführung und Konfliktklärung",
    module: "Bildung",
    type: "Präsenz",
    date: "2026-10-22",
    day: "22",
    month: "OKT",
    place: "Fortbildungszentrum NRW",
    time: "09:00–15:00 Uhr",
    duration: "1 Tag",
    seats: 0,
    category: "Kommunikation",
    desc: "Schwierige Gespräche strukturieren und Konflikte frühzeitig erkennen.",
    approval: true,
  },
];

// What the hero opens on: the course Maria is in the middle of. The progress
// is hers, not the course's, so it lives here and not on the catalogue entry.
const resume = {
  course: 2,
  percent: 62,
  step: "Modul 3 von 5",
  left: "noch etwa 35 Minuten",
  last: "18.09.2026",
};

const people = [
  {
    id: 1,
    name: "Maria Beispiel",
    initials: "MB",
    oe: "Direktion Zentrale Aufgaben",
    role: "Anwender",
    module: "Bildung",
    status: "Aktiv",
  },
  {
    id: 2,
    name: "Jan Muster",
    initials: "JM",
    oe: "Direktion Verkehr",
    role: "SbDA",
    module: "Bildung",
    status: "Aktiv",
  },
  {
    id: 3,
    name: "Lea Beispiel",
    initials: "LB",
    oe: "Direktion Kriminalität",
    role: "Anwender",
    module: "Bildung",
    status: "Gesperrt",
  },
  {
    id: 4,
    name: "Tim Muster",
    initials: "TM",
    oe: "Direktion Gefahrenabwehr",
    role: "ET-Trainer",
    module: "Einsatztraining",
    status: "Aktiv",
  },
  {
    id: 5,
    name: "Alex Beispiel",
    initials: "AB",
    oe: "Direktion Zentrale Aufgaben",
    role: "Sport-Beauftragter",
    module: "Sport",
    status: "Aktiv",
  },
];
